### ISSUE TITLE
32bit exe

### ISSUE THREAD

**Issue by aboc-tset** [ja2-stracciatella/mod-wildfire-maps#12]
Any 32bit exe for install_wildfire_maps.exe?

**Comment by ja2-derek** [comment]
It's built with the default Windows image on Travis, which is probably 64-bit.

But yes, I think JA2:S (and mods installers) ought to be able to run on older machines too.

**Comment by ja2-derek** [comment]
@aboc-tset 32-bit executable is now available from CI builds. You can download the `windows-x86` artifact at https://github.com/ja2-stracciatella/mod-wildfire-maps/actions/runs/505173843.
