### ISSUE TITLE
Does not work on my Catalina Mac :(

### ISSUE THREAD

**Issue by digitaldonkey** [ja2-stracciatella/mod-wildfire-maps#5]
```
~/ja2-building/ja2-stracciatella/_bin/mods/wildfire-maps (v0.17.0 ✔) ᐅ ./install_wildfire_maps --src_dir ~/ja2-building/Jagged\ Alliance\ 2\ Wildfire
Traceback (most recent call last):
  File "install_wildfire_maps.py", line 17, in <module>
ImportError: No module named pathlib
[34698] Failed to execute script install_wildfire_maps
~/ja2-building/ja2-stracciatella/_bin/mods/wildfire-maps (v0.17.0 ✔) ᐅ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
~/ja2-building/ja2-stracciatella/_bin/mods/wildfire-maps (v0.17.0 ✔) ᐅ uname -a
Darwin chuck.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

**Comment by ja2-derek** [comment]
Weird. That library should be bundled in the installer. I will give a check

**Comment by digitaldonkey** [comment]
Can I download the Build PR somewhere?

**Comment by ja2-derek** [comment]
Travis CI builds have been disabled. We need to wait for an org owner to re-enable before we can have PR builds.

So no, you have to build it from source. Or check again in a few hours when org owners comes online.

**Comment by ja2-derek** [comment]
Wondering if @lynxlynxlynx or @selaux can help to enable TravisCI on this repo?

**Comment by lynxlynxlynx** [comment]
I merged the PR, but travis hasn't been set up for this repo yet. It's been acting weird lately too, so I don't even have access to the settings (any more?). Both travis apps are already enabled at the org level.

**Comment by lynxlynxlynx** [comment]
Ok, Derek was right, a migration was needed. The build will appear here:
https://travis-ci.com/github/ja2-stracciatella/mod-wildfire-maps/builds/177204852

**Comment by ja2-derek** [comment]
It should work now https://github.com/ja2-stracciatella/mod-wildfire-maps/releases/tag/0.2.2

Tested on my Mac
